###
GET http://localhost:5000/auth/user
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGZkNmU3NTY5ZjI4OGYyZTlkMDZiNjYiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2OTQzMzIyMTYsImV4cCI6MTY5NDMzNTgxNn0.NQvi2_-88p8w0p8PzJiy_wyNG_CJ_bQVFknDjZKCpOI

###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "user2@admin.com",
    "password":"quang123"
}
###

POST http://localhost:5000/user/register
Content-Type: application/json

{
    "username":"Quang",
    "email": "user3@example.com",
    "password":"quang123"
}
###

POST http://localhost:5000/admin/register
Content-Type: application/json

{
    "username":"Trang",
    "email": "user@admin.com",
    "password":"quang123"
}



