# Use an official Node.js runtime as a base image
FROM node:14 AS test-builder

# Shared directory
WORKDIR /app/shared

# Copy package.json and package-lock.json from services/shared
COPY shared/package*.json .

# Install application dependencies
RUN npm install

# Copy all application files from services/shared
COPY shared/ .

# Switch to order-service directory
WORKDIR /app/order-service

# Copy package.json and package-lock.json from services/auth-service
COPY order-service/package*.json .

# Install application dependencies for auth-service
RUN npm install

# Copy all application files from services/auth-service
COPY order-service .


CMD ["npm", "test"]
